use qrcode::EcLevel as EC;
use qrcode::Version;
pub struct QrData {
    pub version: Version,
    pub ec: EC,
    pub bytes: u32,
}

// Generated by a script which was generated by OpenAI code-davinci-002
pub const QR_DATA: [QrData; 160] = [
    QrData {
        version: Version::Normal(1),
        ec: EC::L,
        bytes: 17,
    },
    QrData {
        version: Version::Normal(1),
        ec: EC::M,
        bytes: 14,
    },
    QrData {
        version: Version::Normal(1),
        ec: EC::Q,
        bytes: 11,
    },
    QrData {
        version: Version::Normal(1),
        ec: EC::H,
        bytes: 7,
    },
    QrData {
        version: Version::Normal(2),
        ec: EC::L,
        bytes: 32,
    },
    QrData {
        version: Version::Normal(2),
        ec: EC::M,
        bytes: 26,
    },
    QrData {
        version: Version::Normal(2),
        ec: EC::Q,
        bytes: 20,
    },
    QrData {
        version: Version::Normal(2),
        ec: EC::H,
        bytes: 14,
    },
    QrData {
        version: Version::Normal(3),
        ec: EC::L,
        bytes: 53,
    },
    QrData {
        version: Version::Normal(3),
        ec: EC::M,
        bytes: 42,
    },
    QrData {
        version: Version::Normal(3),
        ec: EC::Q,
        bytes: 32,
    },
    QrData {
        version: Version::Normal(3),
        ec: EC::H,
        bytes: 24,
    },
    QrData {
        version: Version::Normal(4),
        ec: EC::L,
        bytes: 78,
    },
    QrData {
        version: Version::Normal(4),
        ec: EC::M,
        bytes: 62,
    },
    QrData {
        version: Version::Normal(4),
        ec: EC::Q,
        bytes: 46,
    },
    QrData {
        version: Version::Normal(4),
        ec: EC::H,
        bytes: 34,
    },
    QrData {
        version: Version::Normal(5),
        ec: EC::L,
        bytes: 106,
    },
    QrData {
        version: Version::Normal(5),
        ec: EC::M,
        bytes: 84,
    },
    QrData {
        version: Version::Normal(5),
        ec: EC::Q,
        bytes: 60,
    },
    QrData {
        version: Version::Normal(5),
        ec: EC::H,
        bytes: 44,
    },
    QrData {
        version: Version::Normal(6),
        ec: EC::L,
        bytes: 134,
    },
    QrData {
        version: Version::Normal(6),
        ec: EC::M,
        bytes: 106,
    },
    QrData {
        version: Version::Normal(6),
        ec: EC::Q,
        bytes: 74,
    },
    QrData {
        version: Version::Normal(6),
        ec: EC::H,
        bytes: 58,
    },
    QrData {
        version: Version::Normal(7),
        ec: EC::L,
        bytes: 154,
    },
    QrData {
        version: Version::Normal(7),
        ec: EC::M,
        bytes: 122,
    },
    QrData {
        version: Version::Normal(7),
        ec: EC::Q,
        bytes: 86,
    },
    QrData {
        version: Version::Normal(7),
        ec: EC::H,
        bytes: 64,
    },
    QrData {
        version: Version::Normal(8),
        ec: EC::L,
        bytes: 192,
    },
    QrData {
        version: Version::Normal(8),
        ec: EC::M,
        bytes: 152,
    },
    QrData {
        version: Version::Normal(8),
        ec: EC::Q,
        bytes: 108,
    },
    QrData {
        version: Version::Normal(8),
        ec: EC::H,
        bytes: 84,
    },
    QrData {
        version: Version::Normal(9),
        ec: EC::L,
        bytes: 230,
    },
    QrData {
        version: Version::Normal(9),
        ec: EC::M,
        bytes: 180,
    },
    QrData {
        version: Version::Normal(9),
        ec: EC::Q,
        bytes: 130,
    },
    QrData {
        version: Version::Normal(9),
        ec: EC::H,
        bytes: 98,
    },
    QrData {
        version: Version::Normal(10),
        ec: EC::L,
        bytes: 271,
    },
    QrData {
        version: Version::Normal(10),
        ec: EC::M,
        bytes: 213,
    },
    QrData {
        version: Version::Normal(10),
        ec: EC::Q,
        bytes: 151,
    },
    QrData {
        version: Version::Normal(10),
        ec: EC::H,
        bytes: 119,
    },
    QrData {
        version: Version::Normal(11),
        ec: EC::L,
        bytes: 321,
    },
    QrData {
        version: Version::Normal(11),
        ec: EC::M,
        bytes: 251,
    },
    QrData {
        version: Version::Normal(11),
        ec: EC::Q,
        bytes: 177,
    },
    QrData {
        version: Version::Normal(11),
        ec: EC::H,
        bytes: 137,
    },
    QrData {
        version: Version::Normal(12),
        ec: EC::L,
        bytes: 367,
    },
    QrData {
        version: Version::Normal(12),
        ec: EC::M,
        bytes: 287,
    },
    QrData {
        version: Version::Normal(12),
        ec: EC::Q,
        bytes: 203,
    },
    QrData {
        version: Version::Normal(12),
        ec: EC::H,
        bytes: 155,
    },
    QrData {
        version: Version::Normal(13),
        ec: EC::L,
        bytes: 425,
    },
    QrData {
        version: Version::Normal(13),
        ec: EC::M,
        bytes: 331,
    },
    QrData {
        version: Version::Normal(13),
        ec: EC::Q,
        bytes: 241,
    },
    QrData {
        version: Version::Normal(13),
        ec: EC::H,
        bytes: 177,
    },
    QrData {
        version: Version::Normal(14),
        ec: EC::L,
        bytes: 458,
    },
    QrData {
        version: Version::Normal(14),
        ec: EC::M,
        bytes: 362,
    },
    QrData {
        version: Version::Normal(14),
        ec: EC::Q,
        bytes: 258,
    },
    QrData {
        version: Version::Normal(14),
        ec: EC::H,
        bytes: 194,
    },
    QrData {
        version: Version::Normal(15),
        ec: EC::L,
        bytes: 520,
    },
    QrData {
        version: Version::Normal(15),
        ec: EC::M,
        bytes: 412,
    },
    QrData {
        version: Version::Normal(15),
        ec: EC::Q,
        bytes: 292,
    },
    QrData {
        version: Version::Normal(15),
        ec: EC::H,
        bytes: 220,
    },
    QrData {
        version: Version::Normal(16),
        ec: EC::L,
        bytes: 586,
    },
    QrData {
        version: Version::Normal(16),
        ec: EC::M,
        bytes: 450,
    },
    QrData {
        version: Version::Normal(16),
        ec: EC::Q,
        bytes: 322,
    },
    QrData {
        version: Version::Normal(16),
        ec: EC::H,
        bytes: 250,
    },
    QrData {
        version: Version::Normal(17),
        ec: EC::L,
        bytes: 644,
    },
    QrData {
        version: Version::Normal(17),
        ec: EC::M,
        bytes: 504,
    },
    QrData {
        version: Version::Normal(17),
        ec: EC::Q,
        bytes: 364,
    },
    QrData {
        version: Version::Normal(17),
        ec: EC::H,
        bytes: 280,
    },
    QrData {
        version: Version::Normal(18),
        ec: EC::L,
        bytes: 718,
    },
    QrData {
        version: Version::Normal(18),
        ec: EC::M,
        bytes: 560,
    },
    QrData {
        version: Version::Normal(18),
        ec: EC::Q,
        bytes: 394,
    },
    QrData {
        version: Version::Normal(18),
        ec: EC::H,
        bytes: 310,
    },
    QrData {
        version: Version::Normal(19),
        ec: EC::L,
        bytes: 792,
    },
    QrData {
        version: Version::Normal(19),
        ec: EC::M,
        bytes: 624,
    },
    QrData {
        version: Version::Normal(19),
        ec: EC::Q,
        bytes: 442,
    },
    QrData {
        version: Version::Normal(19),
        ec: EC::H,
        bytes: 338,
    },
    QrData {
        version: Version::Normal(20),
        ec: EC::L,
        bytes: 858,
    },
    QrData {
        version: Version::Normal(20),
        ec: EC::M,
        bytes: 666,
    },
    QrData {
        version: Version::Normal(20),
        ec: EC::Q,
        bytes: 482,
    },
    QrData {
        version: Version::Normal(20),
        ec: EC::H,
        bytes: 382,
    },
    QrData {
        version: Version::Normal(21),
        ec: EC::L,
        bytes: 929,
    },
    QrData {
        version: Version::Normal(21),
        ec: EC::M,
        bytes: 711,
    },
    QrData {
        version: Version::Normal(21),
        ec: EC::Q,
        bytes: 509,
    },
    QrData {
        version: Version::Normal(21),
        ec: EC::H,
        bytes: 403,
    },
    QrData {
        version: Version::Normal(22),
        ec: EC::L,
        bytes: 1003,
    },
    QrData {
        version: Version::Normal(22),
        ec: EC::M,
        bytes: 779,
    },
    QrData {
        version: Version::Normal(22),
        ec: EC::Q,
        bytes: 565,
    },
    QrData {
        version: Version::Normal(22),
        ec: EC::H,
        bytes: 439,
    },
    QrData {
        version: Version::Normal(23),
        ec: EC::L,
        bytes: 1091,
    },
    QrData {
        version: Version::Normal(23),
        ec: EC::M,
        bytes: 857,
    },
    QrData {
        version: Version::Normal(23),
        ec: EC::Q,
        bytes: 611,
    },
    QrData {
        version: Version::Normal(23),
        ec: EC::H,
        bytes: 461,
    },
    QrData {
        version: Version::Normal(24),
        ec: EC::L,
        bytes: 1171,
    },
    QrData {
        version: Version::Normal(24),
        ec: EC::M,
        bytes: 911,
    },
    QrData {
        version: Version::Normal(24),
        ec: EC::Q,
        bytes: 661,
    },
    QrData {
        version: Version::Normal(24),
        ec: EC::H,
        bytes: 511,
    },
    QrData {
        version: Version::Normal(25),
        ec: EC::L,
        bytes: 1273,
    },
    QrData {
        version: Version::Normal(25),
        ec: EC::M,
        bytes: 997,
    },
    QrData {
        version: Version::Normal(25),
        ec: EC::Q,
        bytes: 715,
    },
    QrData {
        version: Version::Normal(25),
        ec: EC::H,
        bytes: 535,
    },
    QrData {
        version: Version::Normal(26),
        ec: EC::L,
        bytes: 1367,
    },
    QrData {
        version: Version::Normal(26),
        ec: EC::M,
        bytes: 1059,
    },
    QrData {
        version: Version::Normal(26),
        ec: EC::Q,
        bytes: 751,
    },
    QrData {
        version: Version::Normal(26),
        ec: EC::H,
        bytes: 593,
    },
    QrData {
        version: Version::Normal(27),
        ec: EC::L,
        bytes: 1465,
    },
    QrData {
        version: Version::Normal(27),
        ec: EC::M,
        bytes: 1125,
    },
    QrData {
        version: Version::Normal(27),
        ec: EC::Q,
        bytes: 805,
    },
    QrData {
        version: Version::Normal(27),
        ec: EC::H,
        bytes: 625,
    },
    QrData {
        version: Version::Normal(28),
        ec: EC::L,
        bytes: 1528,
    },
    QrData {
        version: Version::Normal(28),
        ec: EC::M,
        bytes: 1190,
    },
    QrData {
        version: Version::Normal(28),
        ec: EC::Q,
        bytes: 868,
    },
    QrData {
        version: Version::Normal(28),
        ec: EC::H,
        bytes: 658,
    },
    QrData {
        version: Version::Normal(29),
        ec: EC::L,
        bytes: 1628,
    },
    QrData {
        version: Version::Normal(29),
        ec: EC::M,
        bytes: 1264,
    },
    QrData {
        version: Version::Normal(29),
        ec: EC::Q,
        bytes: 908,
    },
    QrData {
        version: Version::Normal(29),
        ec: EC::H,
        bytes: 698,
    },
    QrData {
        version: Version::Normal(30),
        ec: EC::L,
        bytes: 1732,
    },
    QrData {
        version: Version::Normal(30),
        ec: EC::M,
        bytes: 137,
    },
    QrData {
        version: Version::Normal(30),
        ec: EC::Q,
        bytes: 982,
    },
    QrData {
        version: Version::Normal(30),
        ec: EC::H,
        bytes: 742,
    },
    QrData {
        version: Version::Normal(31),
        ec: EC::L,
        bytes: 184,
    },
    QrData {
        version: Version::Normal(31),
        ec: EC::M,
        bytes: 1452,
    },
    QrData {
        version: Version::Normal(31),
        ec: EC::Q,
        bytes: 103,
    },
    QrData {
        version: Version::Normal(31),
        ec: EC::H,
        bytes: 790,
    },
    QrData {
        version: Version::Normal(32),
        ec: EC::L,
        bytes: 1952,
    },
    QrData {
        version: Version::Normal(32),
        ec: EC::M,
        bytes: 1538,
    },
    QrData {
        version: Version::Normal(32),
        ec: EC::Q,
        bytes: 1112,
    },
    QrData {
        version: Version::Normal(32),
        ec: EC::H,
        bytes: 842,
    },
    QrData {
        version: Version::Normal(33),
        ec: EC::L,
        bytes: 2068,
    },
    QrData {
        version: Version::Normal(33),
        ec: EC::M,
        bytes: 1628,
    },
    QrData {
        version: Version::Normal(33),
        ec: EC::Q,
        bytes: 1168,
    },
    QrData {
        version: Version::Normal(33),
        ec: EC::H,
        bytes: 898,
    },
    QrData {
        version: Version::Normal(34),
        ec: EC::L,
        bytes: 2188,
    },
    QrData {
        version: Version::Normal(34),
        ec: EC::M,
        bytes: 1722,
    },
    QrData {
        version: Version::Normal(34),
        ec: EC::Q,
        bytes: 1228,
    },
    QrData {
        version: Version::Normal(34),
        ec: EC::H,
        bytes: 958,
    },
    QrData {
        version: Version::Normal(35),
        ec: EC::L,
        bytes: 2303,
    },
    QrData {
        version: Version::Normal(35),
        ec: EC::M,
        bytes: 1809,
    },
    QrData {
        version: Version::Normal(35),
        ec: EC::Q,
        bytes: 1283,
    },
    QrData {
        version: Version::Normal(35),
        ec: EC::H,
        bytes: 983,
    },
    QrData {
        version: Version::Normal(36),
        ec: EC::L,
        bytes: 2431,
    },
    QrData {
        version: Version::Normal(36),
        ec: EC::M,
        bytes: 1911,
    },
    QrData {
        version: Version::Normal(36),
        ec: EC::Q,
        bytes: 1351,
    },
    QrData {
        version: Version::Normal(36),
        ec: EC::H,
        bytes: 1051,
    },
    QrData {
        version: Version::Normal(37),
        ec: EC::L,
        bytes: 2563,
    },
    QrData {
        version: Version::Normal(37),
        ec: EC::M,
        bytes: 1989,
    },
    QrData {
        version: Version::Normal(37),
        ec: EC::Q,
        bytes: 1423,
    },
    QrData {
        version: Version::Normal(37),
        ec: EC::H,
        bytes: 1093,
    },
    QrData {
        version: Version::Normal(38),
        ec: EC::L,
        bytes: 2699,
    },
    QrData {
        version: Version::Normal(38),
        ec: EC::M,
        bytes: 2099,
    },
    QrData {
        version: Version::Normal(38),
        ec: EC::Q,
        bytes: 1499,
    },
    QrData {
        version: Version::Normal(38),
        ec: EC::H,
        bytes: 1139,
    },
    QrData {
        version: Version::Normal(39),
        ec: EC::L,
        bytes: 2809,
    },
    QrData {
        version: Version::Normal(39),
        ec: EC::M,
        bytes: 2213,
    },
    QrData {
        version: Version::Normal(39),
        ec: EC::Q,
        bytes: 1579,
    },
    QrData {
        version: Version::Normal(39),
        ec: EC::H,
        bytes: 1219,
    },
    QrData {
        version: Version::Normal(40),
        ec: EC::L,
        bytes: 2953,
    },
    QrData {
        version: Version::Normal(40),
        ec: EC::M,
        bytes: 2331,
    },
    QrData {
        version: Version::Normal(40),
        ec: EC::Q,
        bytes: 1663,
    },
    QrData {
        version: Version::Normal(40),
        ec: EC::H,
        bytes: 1273,
    },
];
